name: Build dotnet

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - dotnet/**
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    strategy:
      fail-fast: false
      matrix:
        tag:
          - "3.1"
          - "5.0"
          - "6.0"
    with:
      tag: ${{ matrix.tag }}
      name: dotnet
