name: Build go

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - go/**
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    strategy:
      fail-fast: false
      matrix:
        tag:
          - "1.15"
          - "1.16"
          - "1.17"
          - "1.18"
          - "1.19"
          - "1.20"
          - "1.21"
    with:
      tag: ${{ matrix.tag }}
      name: go
