name: Build Java OpenJ9

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - java-openj9/**
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      image: java-openj9
