name: Build java-eclipse-temurin

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - java-eclipse-temurin/**
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      image: java-eclipse-temurin
