name: Build nodejs

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - nodejs/**
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    with:
      image: nodejs
