name: Build php

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - php/**
  schedule:
    - cron: "0 7 */10 * *"

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    strategy:
      fail-fast: false
      matrix:
        tag:
          - "5.6"
          - "7.0"
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
    with:
      tag: ${{ matrix.tag }}
      name: php
