name: Build python

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - python/**
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    strategy:
      fail-fast: false
      matrix:
        tag:
          - "2.7"
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
    with:
      tag: ${{ matrix.tag }}
      name: python
