name: Build ruby

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - ruby/**
  schedule:
    - cron: "0 9 */10 * *"

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    strategy:
      fail-fast: false
      matrix:
        tag:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
    with:
      tag: ${{ matrix.tag }}
      name: ruby
