name: Build rust

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - rust/**
  schedule:
    - cron: "0 10 */10 * *"

jobs:
  build:
    uses: ./.github/workflows/_build.yml
    strategy:
      fail-fast: false
      matrix:
        tag:
          - "1"
          - "1.20"
          - "1.30"
          - "1.40"
          - "1.50"
          - "1.60"
          - "1.70"
    with:
      tag: ${{ matrix.tag }}
      name: rust
